[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
# startup_mode = "SimpleFullscreen"

decorations = "Buttonless"
opacity = 0.92
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13.0
